### ISSUE TITLE
Male seeker eye issue

### ISSUE THREAD

**Issue by Kirishikki** [Sebane1/FFXIVLooseTextureCompiler#11] opened 2024-08-05 05:47 UTC
When creating eye mod and selecting masculine seeker eye. It changes nothing in game and changed items says, customization unknown.

**Comment by Sebane1** [comment] 2024-08-05 20:56
Looks like this was caused by me re-ordering lalafells. Forgot to re-order the eye paths too.

**Comment by Kirishikki** [comment] 2024-08-06 10:21
It appears as though highlander female face 4 also has this issue. im very
sorry if im bothering too much. im happy to stop if its obnoxious >.<

**Comment by Sebane1** [comment] 2024-08-06 17:29
Unreported bugs don't get fixed, so its not a problem.
(just means somebody else gets to suffer with the same issue, when I am not aware)

**Comment by Sebane1** [comment] 2024-08-06 21:48
This should now be resolved in v2.0.2.2

**Closed as completed by Sebane1** 2024-08-06 21:48 UTC
